cd /app/widget_library && git pull && mvn clean install
cd /app/code_generator && git pull && mvn clean install
cd /app/css_parser && git pull && mvn clean install
cd /app/html_parser && git pull && mvn clean install
cd /app/Plugin_Converter && git pull && mvn clean install
cd /app/Plugin_HtmlParser && git pull && mvn clean install
cd /app/AndroidJParent && git pull && mvn clean install
cd /app/AndroidJ && git pull && mvn clean install
cd /app/AndroidXJ && git pull && mvn clean install
cd /app/AndroidJMaterial && git pull && mvn clean install
cd /app/AndroidXJConstraintLayout && git pull && mvn clean install
cd /app/AndroidXJDrawerLayout && git pull && mvn clean install
cd /app/AndroidXJGridlayout && git pull && mvn clean install
cd /app/AndroidXJRecyclerView && git pull && mvn clean install
cd /app/AndroidXJToolBar && git pull && mvn clean install
cd /app/CordovaAndroidJLib && git pull && mvn clean install
cd /app/AndroidXJCoordinatorLayout && git pull && mvn clean install
cd /app/AndroidJSnackbar && git pull && mvn clean install
cd /app/AndroidJNavigationView && git pull && mvn clean install
cd /app/SWTParent && git pull && mvn clean install
cd /app/SWTCommon && git pull && mvn clean install
cd /app/Core/core/swt && git pull && mvn clean install
cd /app/Core/layout/swt && git pull && mvn clean install
cd /app/Core/converter/swt && git pull && mvn clean install
cd /app/Core/json/swt && git pull && mvn clean install
cd /app/ConstraintLayout/swt && git pull && mvn clean install
cd /app/GridLayout/swt && git pull && mvn clean install
cd /app/CapInsets/swt && git pull && mvn clean install
cd /app/CapInsets/swt && git pull && mvn clean install
cd /app/CSSBorder/swt && git pull && mvn clean install
cd /app/DateTime/swt && git pull && mvn clean install
cd /app/Drawer/swt && git pull && mvn clean install
cd /app/RecycleView/swt && git pull && mvn clean install
cd /app/ShutterBug/swt && git pull && mvn clean install
cd /app/Toolbar/swt && git pull && mvn clean install
cd /app/Snackbar/swt && git pull && mvn clean install
cd /app/ViewPager/swt && git pull && mvn clean install
cd /app/TextInputLayout/swt && git pull && mvn clean install
cd /app/CoordinatorLayout/swt && git pull && mvn clean install
cd /app/AppBarLayout/swt && git pull && mvn clean install
cd /app/NestedScrollView/swt && git pull && mvn clean install
cd /app/NavigationView/swt && git pull && mvn clean install
cd /app/teavm/classlib && git pull && mvn clean install -Dmaven.test.skip=true
cd /app/teavm/json && git pull && mvn clean install -Dmaven.test.skip=true
cd /app/WebParent && git pull && mvn clean install
cd /app/Core/layout/browser && git pull && mvn clean install
cd /app/Core/core/browser && git pull && mvn clean install
cd /app/Core/converter/browser && git pull && mvn clean install
cd /app/Core/json/browser && git pull && mvn clean install
cd /app/ConstraintLayout/browser && git pull && mvn clean install
cd /app/GridLayout/browser && git pull && mvn clean install
cd /app/CapInsets/browser && git pull && mvn clean install
cd /app/CapInsets/browser && git pull && mvn clean install
cd /app/CSSBorder/browser && git pull && mvn clean install
cd /app/DateTime/browser && git pull && mvn clean install
cd /app/Drawer/browser && git pull && mvn clean install
cd /app/RecycleView/browser && git pull && mvn clean install
cd /app/Toolbar/browser && git pull && mvn clean install
cd /app/Snackbar/browser && git pull && mvn clean install
cd /app/ViewPager/browser && git pull && mvn clean install
cd /app/TextInputLayout/browser && git pull && mvn clean install
cd /app/CoordinatorLayout/browser && git pull && mvn clean install
cd /app/AppBarLayout/browser && git pull && mvn clean install
cd /app/NestedScrollView/browser && git pull && mvn clean install
cd /app/NavigationView/browser && git pull && mvn clean install