# Use an official Java 8 image as the base
FROM node:14.16.0-alpine

#swt
RUN apk add --no-cache xorg-server x11vnc xvfb
RUN apk add --no-cache gtk+3.0 gtk+3.0-dev webkit2gtk webkit2gtk-dev

# Set the DISPLAY environment variable
ENV DISPLAY=:99

# Run Xvfb to create a virtual display
RUN Xvfb :99 -screen 0 1024x768x16 &

# Install Java 1.8
RUN apk add --no-cache openjdk8

# Set the Java version
ENV JAVA_VERSION 1.8
ENV PATH="/usr/lib/jvm/java-1.8-openjdk/bin:$PATH"

# Install Gradle 7.6.2
RUN apk add --no-cache curl
RUN mkdir /opt/gradle
RUN curl -o gradle.zip -k -LO https://services.gradle.org/distributions/gradle-7.6.2-bin.zip
RUN unzip gradle.zip -d /opt/gradle
ENV GRADLE_HOME /opt/gradle/gradle-7.6.2
ENV PATH ${GRADLE_HOME}/bin:${PATH}

# Install ImageMagick 7.1.0-36
RUN apk add --no-cache imagemagick

# Install Cordova
RUN npm install -g cordova@11.0.0

# Install Android SDK
#RUN apk add --no-cache android-sdk
#ENV ANDROID_HOME /opt/android-sdk
#ENV PATH ${ANDROID_HOME}/tools:${PATH}

# Install Git
RUN apk add --no-cache git

# Clone the Cordova project from GitHub
RUN git clone https://github.com/AsheraCordova/HelloWorld.git /app/helloworld
RUN git clone https://github.com/AsheraCordova/playground.git /app/playground
RUN git clone https://github.com/AsheraCordova/InteractivePlayGround.git /app/InteractivePlayGround
RUN git clone https://github.com/AsheraCordova/EcommerceApp.git /app/EcommerceApp
RUN git clone https://github.com/AsheraCordova/TradeApp.git /app/TradeApp


# Set the working directory to /app
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Expose the port for Node.js
EXPOSE 8080